global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wm_backend'
    static_configs:
      - targets: ['backend:8001']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
